Add blog post: Akka licence change one year later
lunatech-labs/lunatech-blog pull request #131
Opened 2023-10-27 14:25 UTC by njlbenn

2023-11-02 08:59 UTC, PeuTit requested changes
Good write up, left a few minor comments, let me know if they are relevant or not!

2023-11-02 08:59 UTC, PeuTit commented on posts/2023-10-27-akka-licence-change-one-year-later.adoc
> +Recently at Lunatech, at the request of many of our clients, we have decided to revisit this topic, specifically with an objective to help our clients manage their exposure to the new BSL licence and
entirel -> entirely

2023-11-02 08:59 UTC, PeuTit commented on posts/2023-10-27-akka-licence-change-one-year-later.adoc
> +It is worth noting, however, a possible migration to Pekko is not without its own risks (and I don’t just mean the general risks of migrating or rewriting software). By migrating to Pekko, one would
... noting, however, **that** a possible ...

2023-11-02 08:59 UTC, PeuTit commented on posts/2023-10-27-akka-licence-change-one-year-later.adoc
> +In that case, the first thing you should do is speak to Lightbend to see how much it is actually going to cost you to stick with Akka and not have to make any changes at all. If it turns out to be mo
cost effective -> cost-effective

2023-11-02 08:59 UTC, PeuTit commented on posts/2023-10-27-akka-licence-change-one-year-later.adoc
> +For applications that are in maintenance mode or where there are only the occasional evolutions and new features, migrating from Akka to Apache Pekko is likely to be the smoothest option. Of course t
Add a comma after 'Of course'

2023-11-02 09:28 UTC, leo-bogastry commented on posts/2023-10-27-akka-licence-change-one-year-later.adoc
> +:title: Akka Licence Change (One Year Later)
we usually also add the language tag here `:lang: en`

2023-11-03 11:24 UTC, PeuTit approved these changes

2023-11-03 11:26 UTC, leo-bogastry approved these changes

2023-11-03 12:05 UTC, leo-bogastry approved these changes

2023-11-03 13:33 UTC, merged