Struggles at the Beginning – Software Testers journal
lunatech-labs/lunatech-blog pull request #67
Opened 2022-11-07 13:20 UTC by TehreemFatima07

2022-11-07 15:22 UTC, teodorovicmilan approved these changes

2022-11-07 15:34 UTC, markehammons requested changes
More review to follow

2022-11-07 16:38 UTC, TehreemFatima07 commented on posts/2022-11-07-software-qa-blog.adoc
> +Next step is to focus on setting the testing strategy for the project and check how the testing culture can be embedded in the team.
Testing culture in general

2022-11-08 07:55 UTC, markehammons commented on posts/2022-11-07-software-qa-blog.adoc
> +Next step is to focus on setting the testing strategy for the project and check how the testing culture can be embedded in the team.
Remove "the" from testing culture then. On the opposite end, "Next step" is a specific step, so put "The" in front.

2022-11-08 10:03 UTC, TehreemFatima07 commented on posts/2022-11-07-software-qa-blog.adoc
> +Next step is to focus on setting the testing strategy for the project and check how the testing culture can be embedded in the team.
Updated

2022-11-08 10:09 UTC, markehammons approved these changes

2022-11-08 15:24 UTC, merged